Adds Throttle, Audit, and Scan
dart-lang/stream_transform pull request #11
Opened 2017-05-06 03:21 UTC by jonahwilliams

Throttle: emits immediately, then swallows values until duration elapses

Audit: like throttle, but it emits the most recent value at the end of the duration.

Scan: a fold which yield the intermediate accumulations.

2017-05-06 04:15 UTC, natebosch requested changes

2017-05-06 04:15 UTC, natebosch commented on lib/src/audit.dart
> +StreamTransformer<T, T> _auditer<T>(Duration duration) {
why do we need a second method for this?

2017-05-06 04:15 UTC, natebosch commented on lib/src/throttle.dart
> +/// at the beginning of the period.
[nit] loks like at least 'at' could fit on the previous line. Can you reflow to 80 characters

2017-05-06 04:15 UTC, natebosch commented on lib/src/audit.dart
> +    if (timer == null) {
[nit] how about `timer ??=`

2017-05-06 04:15 UTC, natebosch commented on lib/src/scan.dart
> +typedef S Func2<T, S>(T item, S accumulation);
we should avoid public typedefs in this package. Can you inline this in the function signature?

2017-05-06 04:15 UTC, natebosch commented on lib/src/scan.dart
> +class _Scan<T, S> implements StreamTransformer<T, S> {
[optional] I think this one can be done without a new class since it can be modeled with `map`

```
StreamTransformer<S, T> scan<S, T>(
        T initialValue, T combine(T previousValue, S element)) =>
    new StreamTransformer<S, T>((stream, cancelOnError) {
      T accumulated = initialValue;
      return stream
          .map((value) => accumulated = combine(accumulated, value))
          .listen(null, cancelOnError: cancelOnError);
    });
````

2017-05-06 04:15 UTC, natebosch commented on lib/src/scan.dart
> +StreamTransformer<T, S> scan<T, S>(Func2<T, S> map, S accumulation) =>
how about `scan(S initialValue, S combine(S previous, T element))` so that it matches the signature of `fold`?

2017-05-06 04:15 UTC, natebosch commented on lib/src/audit.dart
> +/// Creates a StreamTransformer which only emits once per [duration],
I'm not sure I understand the use case - when might we choose to use this over `throttle`?

2017-05-06 04:15 UTC, natebosch commented on test/throttle_test.dart
> +        test('waits for pending value to close', () async {
how do we know it's waited for the pending value? We don't have an `expect` before the value has been emitted

2017-05-06 04:48 UTC, jonahwilliams commented on lib/src/audit.dart
> +/// Creates a StreamTransformer which only emits once per [duration],
A good example might be a text field which auto updates after being modified.  Audit will make more regular updates than debounce, but still always emit the most recent value.

Another way to (mostly) solve the same problem would be to give throttle an optional parameter like `emitLast` which ensures that the last value of the stream is always emitted.

2017-05-06 04:50 UTC, jonahwilliams commented on lib/src/audit.dart
> +StreamTransformer<T, T> _auditer<T>(Duration duration) {
No reason, I will fix this here and in throttle

2017-05-06 04:51 UTC, natebosch commented on lib/src/audit.dart
> +/// Creates a StreamTransformer which only emits once per [duration],
Ah cool. I think it could be helpful to call out the differences from debounce and throttle in the doc comment.

2017-05-06 04:54 UTC, jonahwilliams commented on lib/src/scan.dart
> +class _Scan<T, S> implements StreamTransformer<T, S> {
Done.

Note to self, remember that assignment is an expression

2017-05-06 04:54 UTC, jonahwilliams commented on test/throttle_test.dart
> +        test('waits for pending value to close', () async {
Actually I think this test doesn't apply to throttle, since it never waits.  Removed.

2017-05-06 04:54 UTC, jonahwilliams commented on lib/src/scan.dart
> +StreamTransformer<T, S> scan<T, S>(Func2<T, S> map, S accumulation) =>
Done

2017-05-06 04:54 UTC, jonahwilliams commented on lib/src/scan.dart
> +typedef S Func2<T, S>(T item, S accumulation);
Done

2017-05-06 04:54 UTC, jonahwilliams commented on lib/src/throttle.dart
> +/// at the beginning of the period.
Done

2017-05-06 04:54 UTC, jonahwilliams commented on lib/src/audit.dart
> +    if (timer == null) {
Done

2017-05-06 05:00 UTC, natebosch approved these changes
Looks good.

Thanks for the contribution!

Could you also update README and CHANGELOG?

2017-05-06 20:36 UTC, jonahwilliams commented
Done

2017-05-06 22:11 UTC, natebosch commented on lib/src/audit.dart
> +/// a period.  Alwyas introduces a delay of at most [duration].
One last nit: typo in Always.

2017-05-07 04:36 UTC, jonahwilliams commented on lib/src/audit.dart
> +/// a period.  Alwyas introduces a delay of at most [duration].
Woops, Done

2017-05-07 05:02 UTC, merged